
services:
  - type: web
    name: minecraft-afk-bot
    env: node
    runtime: node
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "18"
